<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>TOP_Packets</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TOP-Network\TOP-Network.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Client\" />
  </ItemGroup>

</Project>
