<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../TOP-Records/TOP-Records/TOP-Records.csproj" />
    <ProjectReference Include="../TOP-Network/TOP-Network.csproj" />
  </ItemGroup>

</Project>
