<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TOP-Network\TOP-Network.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="test\address.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\bool.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\byte.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\date.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\double.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\float.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\int.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\list.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\long.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\person.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\sbyte.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\short.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\string.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\uint.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\ulong.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="test\ushort.tst">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
