# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        path: 'TOP-Network'
    - uses: actions/checkout@v4
      with:
        ref: main
        repository: BlitzDaWolf/TOP-Records
        token: ${{ secrets.GH_PAT }}
        path: 'TOP-Records'
    - uses: actions/checkout@v4
      with:
        ref: main
        repository: BlitzDaWolf/TOP_Utils
        token: ${{ secrets.GH_PAT }}
        path: 'TOP_Utils'
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./TOP-Network
      run: dotnet restore --property WarningLevel=0
    - name: Build
      working-directory: ./TOP-Network
      run: dotnet build --no-restore --property WarningLevel=0
    - name: Test
      working-directory: ./TOP-Network
      run: dotnet test --no-build --verbosity normal
